/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daw.ejercicio3_interfaz_grafica;

/**
 *
 * @author portb
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        buttonGroup1.add(this.Opcion1);
        buttonGroup1.add(this.Opcion2);
        buttonGroup1.add(this.Opcion3);

        buttonGroup2.add(this.Opcion1Espejo);
        buttonGroup2.add(this.OpcionEspejo2);
        buttonGroup2.add(this.Opcion3Espejo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Opcion1 = new javax.swing.JRadioButton();
        Opcion2 = new javax.swing.JRadioButton();
        Opcion3 = new javax.swing.JRadioButton();
        Opcion4 = new javax.swing.JCheckBox();
        Opcion5 = new javax.swing.JCheckBox();
        Opcion6 = new javax.swing.JCheckBox();
        Opcion7 = new javax.swing.JTextField();
        Opcion9 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        Opcion8 = new javax.swing.JComboBox<>();
        Opcion8Espejo = new javax.swing.JComboBox<>();
        Opcion1Espejo = new javax.swing.JRadioButton();
        OpcionEspejo2 = new javax.swing.JRadioButton();
        Opcion3Espejo = new javax.swing.JRadioButton();
        Opcion4Espejo = new javax.swing.JCheckBox();
        Opcion5Espejo = new javax.swing.JCheckBox();
        Opcion6Espejo = new javax.swing.JCheckBox();
        Opcion7Espejo = new javax.swing.JTextField();
        Opcion9Espejo = new javax.swing.JSpinner();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Original");

        Opcion1.setText("Opcion 1");
        Opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion1ActionPerformed(evt);
            }
        });

        Opcion2.setText("Opcion 2");
        Opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion2ActionPerformed(evt);
            }
        });

        Opcion3.setText("Opcion 3");
        Opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion3ActionPerformed(evt);
            }
        });

        Opcion4.setText("Opcion 4");
        Opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion4ActionPerformed(evt);
            }
        });

        Opcion5.setText("Opcion 5");
        Opcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion5ActionPerformed(evt);
            }
        });

        Opcion6.setText("Opcion 6");
        Opcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion6ActionPerformed(evt);
            }
        });

        Opcion7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Opcion7KeyTyped(evt);
            }
        });

        Opcion9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Opcion9StateChanged(evt);
            }
        });

        Opcion8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Opcion8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Opcion8ItemStateChanged(evt);
            }
        });

        Opcion8Espejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Opcion8Espejo.setEnabled(false);

        Opcion1Espejo.setText("Opcion 1");
        Opcion1Espejo.setEnabled(false);
        Opcion1Espejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion1EspejoActionPerformed(evt);
            }
        });

        OpcionEspejo2.setText("Opcion 2");
        OpcionEspejo2.setEnabled(false);

        Opcion3Espejo.setText("Opcion 3");
        Opcion3Espejo.setEnabled(false);

        Opcion4Espejo.setText("Opcion 4");
        Opcion4Espejo.setEnabled(false);

        Opcion5Espejo.setText("Opcion 5");
        Opcion5Espejo.setEnabled(false);

        Opcion6Espejo.setText("Opcion 6");
        Opcion6Espejo.setEnabled(false);

        Opcion7Espejo.setEnabled(false);

        Opcion9Espejo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Opcion3)
                                    .addComponent(Opcion2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Opcion1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Opcion6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Opcion5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Opcion4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Opcion7)
                                    .addComponent(Opcion9)
                                    .addComponent(Opcion8, 0, 112, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Opcion3Espejo)
                            .addComponent(Opcion1Espejo)
                            .addComponent(OpcionEspejo2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Opcion6Espejo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Opcion5Espejo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Opcion4Espejo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Opcion7Espejo)
                            .addComponent(Opcion9Espejo)
                            .addComponent(Opcion8Espejo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Opcion4)
                        .addComponent(Opcion7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Opcion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opcion8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Opcion2)
                        .addComponent(Opcion5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Opcion6)
                        .addComponent(Opcion9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Opcion3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion4Espejo)
                    .addComponent(Opcion7Espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Opcion1Espejo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opcion8Espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(OpcionEspejo2)
                        .addComponent(Opcion5Espejo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Opcion6Espejo)
                        .addComponent(Opcion9Espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Opcion3Espejo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Opcion1EspejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion1EspejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion1EspejoActionPerformed

    private void Opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion1ActionPerformed
        this.Opcion1Espejo.setSelected(this.Opcion1.isSelected());
    }//GEN-LAST:event_Opcion1ActionPerformed

    private void Opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion2ActionPerformed
        this.OpcionEspejo2.setSelected(this.Opcion2.isSelected());
    }//GEN-LAST:event_Opcion2ActionPerformed

    private void Opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion3ActionPerformed
        this.Opcion3Espejo.setSelected(this.Opcion3.isSelected());
    }//GEN-LAST:event_Opcion3ActionPerformed

    private void Opcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion4ActionPerformed
       this.Opcion4Espejo.setSelected(this.Opcion4.isSelected());
    }//GEN-LAST:event_Opcion4ActionPerformed

    private void Opcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion5ActionPerformed
        this.Opcion5Espejo.setSelected(this.Opcion5.isSelected());
    }//GEN-LAST:event_Opcion5ActionPerformed

    private void Opcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion6ActionPerformed
        this.Opcion6Espejo.setSelected(this.Opcion6.isSelected());
    }//GEN-LAST:event_Opcion6ActionPerformed

    private void Opcion7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Opcion7KeyTyped
        this.Opcion7Espejo.setText(this.Opcion7.getText());
    }//GEN-LAST:event_Opcion7KeyTyped

    private void Opcion8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Opcion8ItemStateChanged
        this.Opcion8Espejo.setSelectedIndex(this.Opcion8.getSelectedIndex());
    }//GEN-LAST:event_Opcion8ItemStateChanged

    private void Opcion9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Opcion9StateChanged
        this.Opcion9Espejo.setValue((Integer)this.Opcion9.getValue());
    }//GEN-LAST:event_Opcion9StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Opcion1;
    private javax.swing.JRadioButton Opcion1Espejo;
    private javax.swing.JRadioButton Opcion2;
    private javax.swing.JRadioButton Opcion3;
    private javax.swing.JRadioButton Opcion3Espejo;
    private javax.swing.JCheckBox Opcion4;
    private javax.swing.JCheckBox Opcion4Espejo;
    private javax.swing.JCheckBox Opcion5;
    private javax.swing.JCheckBox Opcion5Espejo;
    private javax.swing.JCheckBox Opcion6;
    private javax.swing.JCheckBox Opcion6Espejo;
    private javax.swing.JTextField Opcion7;
    private javax.swing.JTextField Opcion7Espejo;
    private javax.swing.JComboBox<String> Opcion8;
    private javax.swing.JComboBox<String> Opcion8Espejo;
    private javax.swing.JSpinner Opcion9;
    private javax.swing.JSpinner Opcion9Espejo;
    private javax.swing.JRadioButton OpcionEspejo2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
